# Generated by Django 3.1.4 on 2021-02-07 09:12

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('class_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('total_student', models.IntegerField(default=0)),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.department')),
                ('major_id', models.ForeignKey(db_column='major_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.major')),
            ],
            options={
                'db_table': 't_class_info',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_gender', models.CharField(default='男', max_length=2)),
                ('student_nation', models.CharField(default='汉族', max_length=10)),
                ('student_grade', student.models.YearField(default=2021)),
                ('birth_date', models.DateField(default='2021-01-01')),
                ('length_of_schooling', models.IntegerField(default=4)),
                ('political_status', models.CharField(default='群众', max_length=20)),
                ('native_place', models.CharField(default='', max_length=50)),
                ('enrollment_date', models.DateField(default='2020-09-01')),
                ('dormitory_addr', models.CharField(default='南邮通达学生宿舍XX栋', max_length=50)),
                ('password', models.CharField(default=models.CharField(max_length=12, primary_key=True, serialize=False), max_length=20)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=11)),
                ('id_number', models.CharField(default='', max_length=18)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='student.classinfo')),
                ('counselor_id', models.ForeignKey(db_column='counselor_id', on_delete=django.db.models.deletion.DO_NOTHING, to='counselor.counselor')),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.department')),
                ('major_id', models.ForeignKey(db_column='major_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.major')),
            ],
            options={
                'db_table': 't_student_info',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_type', models.CharField(default='必修', max_length=10)),
                ('course_grade', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('semester', models.IntegerField(default=1)),
                ('part_time_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('get_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('postscript', models.CharField(default='', max_length=20)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.course')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
            options={
                'db_table': 't_score_info',
            },
        ),
    ]
