# Generated by Django 3.1.4 on 2021-02-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('counselor_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('counselor_name', models.CharField(max_length=50)),
                ('counselor_gender', models.CharField(default='男', max_length=2)),
                ('counselor_nation', models.CharField(default='汉族', max_length=10)),
                ('phone', models.CharField(default='', max_length=11)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default=models.CharField(max_length=8, primary_key=True, serialize=False), max_length=2)),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.department')),
            ],
            options={
                'db_table': 't_counselor_info',
            },
        ),
    ]
