# Generated by Django 3.1.4 on 2021-02-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_department_info',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('major_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=50)),
                ('required_grade', models.DecimalField(decimal_places=2, default=80, max_digits=5)),
                ('elective_grade', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.department')),
            ],
            options={
                'db_table': 't_major_info',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(default='', max_length=50)),
                ('course_duration', models.IntegerField(default=32)),
                ('course_grade', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('course_type', models.CharField(default='必修', max_length=10)),
                ('department_id', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.department')),
                ('major_id', models.ForeignKey(db_column='major_id', on_delete=django.db.models.deletion.DO_NOTHING, to='course.major')),
            ],
            options={
                'db_table': 't_course_info',
            },
        ),
    ]
